/**
 * js/event.js
 * ---------------------------------------------------------------------------
 * Event detail page controller.
 *
 * Required behaviour from the assessment brief, and where it happens here:
 *   * "only displays the details for the specific event selected from the Home
 *      or Search pages ... utilise URL query strings or Local Storage to pass
 *      the event id and fetch the correct data via your API"
 *        -> readEventId() reads ?id=7; the last id the visitor opened is also
 *           remembered in localStorage as a fallback, so the page still works
 *           if the query string is lost.
 *   * "display all relevant event details retrieved from your API with a
 *      professional and engaging layout"
 *        -> renderEvent() builds the hero, the facts list, the full
 *           description, the purpose and the organisation panel.
 *   * "ticket information (the price, or even a free one)"
 *        -> buildTicketPanel() lists every ticket tier and marks free tiers.
 *   * "Goal vs. Progress (for a specific charity goal)"
 *        -> dom.js progressBar() draws the goal against the donations total.
 *
 * Assessment 3 additions
 *   * The Register button now LINKS to registration.html?id=<id> instead of
 *     opening the "under construction" dialog. The brief requires it to
 *     "correctly link to the new Event Registration Page".
 *   * The inline demonstration form that A2 carried has been REMOVED from this
 *     page. It was a non-functional placeholder, and A3 gives registration a
 *     dedicated page - keeping a second, dead form here would be confusing.
 *   * A new panel lists the registrations for the event, retrieved through
 *     GET /api/events/:id (which A3 extended to include them), newest purchase
 *     first.
 *   * An optional weather panel shows the Open-Meteo forecast for the event day.
 */
import { getEventById, ApiError } from './api.js';
import { initLayout } from './nav.js';
import {
  el,
  select,
  imageUrl,
  stateBadge,
  progressBar,
  formatDate,
  formatDateRange,
  formatShortDate,
  formatTime,
  formatPrice,
  formatCurrency,
  showError,
} from './dom.js';
import { REGISTRATION_PAGE } from './config.js';
import { fetchEventForecast, weatherCodeKey, weatherGlyph, isWetWeather } from './weather.js';
import { t, onLanguageChange } from './i18n.js';

const STORAGE_KEY = 'charity-events:last-viewed-event-id';

/* ------------------------------------------------------------------ */
/* Startup                                                             */
/* ------------------------------------------------------------------ */
document.addEventListener('DOMContentLoaded', () => {
  initLayout();

  const eventId = readEventId();

  if (!eventId) {
    renderMissingId();
  } else {
    loadEvent(eventId);
  }

  // The whole detail page is generated by this module, so a language change has
  // to rebuild it from the data that is already in memory rather than re-fetch.
  onLanguageChange(() => {
    if (currentEvent) {
      renderEvent(currentEvent);
    } else {
      renderMissingId();
    }
    appendBackLink(select('#event-root'));
  });
});

/** The event currently on screen, kept so a language change can re-render it. */
let currentEvent = null;

/**
 * The forecast already fetched for the current event, so a language change
 * rebuilds the panel from memory instead of calling Open-Meteo again.
 */
let currentForecast = null;

/** Aborts an in-flight forecast request when a new event is opened. */
let forecastController = null;

/* ------------------------------------------------------------------ */
/* Reading the event id                                                */
/* ------------------------------------------------------------------ */

/**
 * Get the event id, preferring the query string (the method the brief
 * suggests) and falling back to localStorage.
 */
function readEventId() {
  const fromQuery = new URLSearchParams(window.location.search).get('id');

  if (fromQuery !== null && fromQuery !== '') {
    // Remember it for a later visit without the query string.
    try {
      window.localStorage.setItem(STORAGE_KEY, fromQuery);
    } catch (error) {
      // Private browsing can block localStorage; the query string still works.
    }
    return fromQuery;
  }

  try {
    const stored = window.localStorage.getItem(STORAGE_KEY);
    if (stored) {
      // Put the id back into the address bar so the URL stays shareable.
      window.history.replaceState({}, '', `?id=${encodeURIComponent(stored)}`);
      return stored;
    }
  } catch (error) {
    // ignore
  }

  return null;
}

/* ------------------------------------------------------------------ */
/* Loading and rendering                                               */
/* ------------------------------------------------------------------ */
async function loadEvent(eventId) {
  const root = select('#event-root');

  try {
    const event = await getEventById(eventId);
    renderEvent(event);
    loadForecast(event);
  } catch (error) {
    if (error instanceof ApiError && error.status === 404) {
      showError(root, error.message, [t('error.eventSuspendedHint')]);
    } else {
      showError(root, error.friendlyMessage || t('error.eventLoadFailed'), error.details);
    }
    appendBackLink(root);
  }
}

/**
 * Fetch the optional forecast and swap the placeholder panel for the result.
 *
 * Kept separate from renderEvent() on purpose: the forecast is a bonus, so it
 * must never delay or break the event details, and a language change must not
 * trigger another network call.
 */
async function loadForecast(event) {
  if (forecastController) forecastController.abort();
  forecastController = new AbortController();

  const placeholder = select('#weather-panel');
  if (!placeholder) return;

  currentForecast = await fetchEventForecast(event, {
    signal: forecastController.signal,
  });

  // The visitor may have navigated (or the language may have changed) while the
  // request was in flight, in which case the placeholder is gone.
  const target = select('#weather-panel');
  if (!target || !currentEvent || currentEvent.eventId !== event.eventId) return;

  if (currentForecast) {
    target.replaceWith(buildWeatherPanel(event, currentForecast));
  } else {
    // Remove the placeholder entirely: either the venue has no coordinates, the
    // event is too far away, or the weather service is unreachable. None of
    // those deserve an error box on a page that is otherwise fine.
    target.remove();
  }
}

/** Build the complete page for one event. */
function renderEvent(event) {
  const root = select('#event-root');

  currentEvent = event;
  document.title = t('event.detailTitle', { name: event.eventName });
  select('#breadcrumb-event').textContent = event.eventName;

  root.replaceChildren(buildHero(event), buildDetailSection(event));

  // A re-render (a language change) has to restore the forecast panel too.
  if (currentForecast) {
    const placeholder = select('#weather-panel');
    if (placeholder) placeholder.replaceWith(buildWeatherPanel(event, currentForecast));
  }
}

/* ------------------------------------------------------------------ */
/* Hero                                                                */
/* ------------------------------------------------------------------ */
function buildHero(event) {
  const section = el('section', { className: 'event-hero' });
  const container = el('div', { className: 'container' });
  const grid = el('div', { className: 'event-hero__grid' });

  /* --- left: the headline facts ---------------------------------- */
  const copy = el('div');

  const meta = el('div', { className: 'event-hero__meta' });
  meta.append(stateBadge(event.eventState));
  meta.append(
    el('span', {
      className: 'chip',
      text: event.categoryName || t('state.charityEvent'),
    })
  );
  meta.append(
    el('span', {
      className: 'price',
      text: priceSummary(event),
    })
  );

  const title = el('h1', { text: event.eventName });

  const lead = el('p', { className: 'event-hero__lead', text: event.shortDescription });

  const facts = el('ul', { className: 'fact-list' });
  [
    [t('event.detailDate'), formatDate(event.dateStart)],
    [t('event.detailTime'), `${formatTime(event.startTime)} - ${formatTime(event.endTime)}`],
    [
      t('event.detailVenue'),
      `${event.venueName}${event.address && event.address !== 'N/A' ? `, ${event.address}` : ''}`,
    ],
    [t('event.detailLocation'), `${event.city} ${event.state || ''} ${event.postcode || ''}`.trim()],
    [t('event.detailOrganiser'), event.organizationName],
    [
      t('event.detailCapacity'),
      event.capacity
        ? t('event.capacityPlaces', { count: event.capacity })
        : t('event.capacityUnlimited'),
    ],
    // A3: how many registrations the event has attracted so far.
    [
      t('event.registrationsTotal'),
      t('event.registeredCount', { count: event.registrationCount || 0 }),
    ],
  ].forEach(([label, value]) => {
    const item = el('li');
    item.append(
      el('span', { className: 'fact-list__label', text: label }),
      el('span', { className: 'fact-list__value', text: value })
    );
    facts.append(item);
  });

  copy.append(meta, title, lead, facts);

  /* --- right: image ---------------------------------------------- */
  const media = el('div', { className: 'event-hero__media' });
  media.append(
    el('img', {
      attributes: {
        src: imageUrl(event),
        alt: t('a11y.eventIllustration', { name: event.eventName }),
        width: '720',
        height: '450',
      },
    })
  );

  grid.append(copy, media);
  container.append(grid);
  section.append(container);
  return section;
}

/** "Free entry", "From $20.00" or "Tickets from $20.00 to $480.00". */
function priceSummary(event) {
  const prices = (event.ticketTypes || []).map((ticket) => ticket.price);

  if (event.isFree || (prices.length > 0 && prices.every((price) => price === 0))) {
    return t('event.freeEntry');
  }
  if (prices.length === 0) {
    return t('event.contactForPrices');
  }

  const min = Math.min(...prices.filter((price) => price > 0));
  const max = Math.max(...prices);
  if (min === max) return t('event.ticketsSingle', { price: formatPrice(min) });
  return t('event.ticketsFromTo', { min: formatPrice(min), max: formatPrice(max) });
}

/* ------------------------------------------------------------------ */
/* Main content + sidebar                                              */
/* ------------------------------------------------------------------ */
function buildDetailSection(event) {
  const container = el('div', { className: 'container' });
  const grid = el('div', { className: 'detail-grid' });

  grid.append(buildProse(event), buildSideColumn(event));
  container.append(grid);
  return container;
}

/** Full description, purpose, the registration list and organiser information. */
function buildProse(event) {
  const prose = el('div', { className: 'prose' });

  prose.append(el('h2', { text: t('event.aboutHeading') }));
  // The description is one paragraph per blank line, so a long text stays
  // readable without trusting it as HTML.
  event.description
    .split(/\n+/)
    .filter((paragraph) => paragraph.trim() !== '')
    .forEach((paragraph) => {
      prose.append(el('p', { text: paragraph.trim() }));
    });

  prose.append(el('h2', { text: t('event.purposeHeading') }));
  prose.append(el('p', { text: event.purpose }));

  prose.append(el('h2', { text: t('event.fundsHeading') }));
  const uses = el('ul');
  [t('event.funds1'), t('event.funds2'), t('event.funds3')].forEach((line) =>
    uses.append(el('li', { text: line }))
  );
  prose.append(uses);

  // A3: the registration list, and the weather panel, both sit in the main
  // column so the wide table has room to breathe.
  prose.append(buildRegistrationsSection(event));
  prose.append(buildWeatherPlaceholder(event));

  prose.append(el('h2', { text: t('event.accessHeading') }));
  prose.append(el('p', { text: t('event.accessBody') }));

  prose.append(el('h2', { text: t('event.statusHeading') }));
  prose.append(
    el('p', {
      text:
        event.eventState === 'past'
          ? t('event.statusPast', { date: formatDate(event.dateEnd) })
          : event.eventState === 'ongoing'
            ? t('event.statusOngoing')
            : t('event.statusUpcoming', { date: formatDateRange(event) }),
    })
  );

  return prose;
}

/* ------------------------------------------------------------------ */
/* A3: registrations for this event                                    */
/* ------------------------------------------------------------------ */

/**
 * The list of registrations, newest purchase first.
 *
 * The order is decided by the API (`ORDER BY registered_at DESC`), so this
 * function renders the array in the order it arrives and does not sort again -
 * one place decides the order, which is what the brief asks for: "sorted by the
 * latest date when the tickets were purchased".
 *
 * Built as a real <table> because the data is tabular, with a caption and
 * column headers so a screen reader can navigate it. The CSS that styles it
 * lives in the "registrations table" section of styles.css.
 */
function buildRegistrationsSection(event) {
  const registrations = event.registrations || [];

  const heading = el('h2', {
    text: t('event.registrationsHeading'),
    attributes: { id: 'registrations-heading' },
  });
  const section = el('section', {
    className: 'registrations',
    attributes: { 'aria-labelledby': 'registrations-heading' },
  });
  section.append(heading);

  if (registrations.length === 0) {
    section.append(
      el('p', { className: 'registrations__empty', text: t('event.registrationsEmpty') })
    );
    return section;
  }

  section.append(
    el('p', {
      className: 'registrations__lead',
      text: t('event.registrationsLead', { count: registrations.length }),
    })
  );

  const wrapper = el('div', { className: 'table-wrap' });
  const table = el('table', { className: 'data-table' });

  const caption = el('caption', {
    className: 'sr-only',
    text: t('event.registrationsHeading'),
  });
  table.append(caption);

  const head = el('thead');
  const headRow = el('tr');
  [
    t('event.registrationsName'),
    t('event.registrationsTier'),
    t('event.registrationsTickets'),
    t('event.registrationsValue'),
    t('event.registrationsDate'),
  ].forEach((label, index) => {
    headRow.append(
      el('th', {
        text: label,
        attributes: { scope: 'col', class: index >= 2 ? 'is-numeric' : '' },
      })
    );
  });
  head.append(headRow);
  table.append(head);

  const body = el('tbody');
  registrations.forEach((registration) => {
    const row = el('tr');

    // The attendee cell carries the name plus the contact details underneath,
    // so the table stays narrow on a phone while still showing the email.
    const attendee = el('th', { attributes: { scope: 'row' } });
    attendee.append(
      el('span', { className: 'data-table__primary', text: registration.attendeeName })
    );
    const contact = [registration.attendeeEmail, registration.attendeePhone]
      .filter(Boolean)
      .join(' · ');
    if (contact) {
      attendee.append(el('span', { className: 'data-table__secondary', text: contact }));
    }
    // A registration without a name would be a database problem, not a display
    // one, but a fallback keeps the table readable either way.
    if (!registration.attendeeName) {
      attendee.textContent = t('event.registrationsLogin') + ' ' + registration.registrationId;
    }

    row.append(
      attendee,
      el('td', {
        text: registration.ticketName || t('event.tierGeneral'),
      }),
      el('td', {
        className: 'is-numeric',
        text: String(registration.ticketsPurchased),
      }),
      el('td', {
        className: 'is-numeric',
        text: formatCurrency(registration.totalAmount),
      }),
      el('td', {
        // registeredAt is a DATETIME string; only the date is useful in a table,
        // and the exact time is kept in the title attribute.
        text: formatShortDate(String(registration.registeredAt).slice(0, 10)),
        attributes: { title: registration.registeredAt },
      })
    );
    body.append(row);
  });
  table.append(body);

  // A totals row, so the "how much has this raised in tickets" question is
  // answered without adding up the column by hand.
  const foot = el('tfoot');
  const footRow = el('tr');
  footRow.append(
    el('th', { text: t('event.registrationsTotal'), attributes: { scope: 'row' } }),
    el('td', { text: '' }),
    el('td', {
      className: 'is-numeric',
      text: String(event.totalTicketsSold || 0),
    }),
    el('td', {
      className: 'is-numeric',
      text: formatCurrency(
        registrations.reduce((sum, row) => sum + Number(row.totalAmount || 0), 0)
      ),
    }),
    el('td', { text: '' })
  );
  foot.append(footRow);
  table.append(foot);

  wrapper.append(table);
  section.append(wrapper);
  return section;
}

/* ------------------------------------------------------------------ */
/* A3: optional Open-Meteo forecast                                    */
/* ------------------------------------------------------------------ */

/**
 * A placeholder that loadForecast() replaces (or removes).
 *
 * A placeholder rather than a fetch inside renderEvent() because the forecast
 * is a separate, optional network call to a third party: the page must be
 * complete and usable before - and even without - it.
 */
function buildWeatherPlaceholder() {
  const section = el('section', {
    className: 'weather',
    attributes: { id: 'weather-panel', 'aria-live': 'polite' },
  });
  section.append(el('h2', { text: t('weather.heading') }));
  section.append(el('p', { className: 'weather__loading', text: t('weather.loading') }));
  return section;
}

/** The forecast panel, once the data has arrived. */
function buildWeatherPanel(event, forecast) {
  const section = el('section', {
    className: 'weather',
    attributes: { id: 'weather-panel' },
  });

  section.append(el('h2', { text: t('weather.heading') }));
  section.append(
    el('p', {
      className: 'weather__lead',
      // The venue name already contains its city ("Lismore Riverside Park"), so
      // the lead puts the venue first and the city in brackets rather than
      // gluing the two together, which produced "LismoreLismore Riverside Park".
      text: t('weather.lead', {
        venue: forecast.venueName,
        city: forecast.city,
        date: formatDate(forecast.date),
      }),
    })
  );

  const card = el('div', {
    className: isWetWeather(forecast.weatherCode)
      ? 'weather__card weather__card--wet'
      : 'weather__card',
  });

  const glyph = el('span', {
    className: 'weather__glyph',
    text: weatherGlyph(forecast.weatherCode),
    attributes: { 'aria-hidden': 'true' },
  });

  const summary = el('div', { className: 'weather__summary' });
  summary.append(
    el('span', {
      className: 'weather__code',
      text: t(weatherCodeKey(forecast.weatherCode)),
    })
  );
  const temperatures = [];
  if (forecast.temperatureMax !== null) {
    temperatures.push(`${t('weather.high')} ${Math.round(forecast.temperatureMax)}°C`);
  }
  if (forecast.temperatureMin !== null) {
    temperatures.push(`${t('weather.low')} ${Math.round(forecast.temperatureMin)}°C`);
  }
  if (temperatures.length > 0) {
    summary.append(el('span', { className: 'weather__temps', text: temperatures.join('  ·  ') }));
  }

  card.append(glyph, summary);

  const details = el('ul', { className: 'weather__details' });
  if (forecast.rainChance !== null) {
    details.append(
      el('li', {
        text: `${t('weather.rainChance')}: ${Math.round(forecast.rainChance)}%`,
      })
    );
  }
  if (forecast.windMax !== null) {
    details.append(
      el('li', {
        text: `${t('weather.wind')}: ${Math.round(forecast.windMax)} km/h`,
      })
    );
  }
  if (details.childElementCount > 0) card.append(details);

  section.append(card);
  section.append(el('p', { className: 'weather__hint', text: t('weather.outdoorHint') }));
  section.append(
    el('p', {
      className: 'weather__credit',
      text: t('weather.attribution'),
    })
  );

  return section;
}

/** Registration, tickets and the goal progress bar. */
function buildSideColumn(event) {
  const column = el('div', { className: 'side-column' });

  column.append(
    buildGoalPanel(event),
    buildTicketPanel(event),
    buildOrganiserPanel(event)
  );

  return column;
}

/** Goal vs progress - the fundraising goal against the donations recorded. */
function buildGoalPanel(event) {
  const panel = el('div', { className: 'panel panel--brand' });
  panel.append(el('h2', { text: t('event.goalHeading') }));
  panel.append(el('p', { text: t('event.goalLead', { organisation: event.organizationName }) }));
  panel.append(progressBar(event));

  const summary = el('ul', { className: 'contact-list' });
  [
    [t('event.goalRow'), formatCurrency(event.goalAmount)],
    [t('event.raisedRow'), formatCurrency(event.raisedAmount)],
    [t('event.remainingRow'), formatCurrency(Math.max(event.goalAmount - event.raisedAmount, 0))],
    [t('event.donationsRow'), t('event.donationsValue', { count: event.donationCount || 0 })],
  ].forEach(([label, value]) => {
    const item = el('li');
    item.append(el('span', { text: label }), el('span', { text: value }));
    summary.append(item);
  });
  panel.append(summary);

  return panel;
}

/**
 * Ticket tiers and the Register button.
 *
 * A3: the button is now an ANCHOR to the registration page carrying the event
 * id in the query string, which is the navigation the brief asks for. A past
 * event shows a disabled button instead, because there is nothing left to book.
 */
function buildTicketPanel(event) {
  const panel = el('div', { className: 'panel panel--accent' });
  panel.append(el('h2', { text: t('event.ticketsHeading') }));

  const tickets = event.ticketTypes || [];

  if (tickets.length === 0) {
    panel.append(el('p', { text: t('event.ticketsMissing') }));
  } else {
    const list = el('ul', { className: 'ticket-list' });
    tickets.forEach((ticket) => {
      const item = el('li', {
        className: ticket.price === 0 ? 'ticket ticket--free' : 'ticket',
      });

      const name = el('span', { className: 'ticket__name', text: ticket.ticketName });
      if (ticket.description) {
        name.append(el('span', { className: 'ticket__desc', text: ticket.description }));
      }
      if (ticket.quantityAvailable !== null && ticket.quantityAvailable !== undefined) {
        name.append(
          el('span', {
            className: 'ticket__availability',
            text:
              ticket.quantityAvailable > 0
                ? t('event.availableCount', { count: ticket.quantityAvailable })
                : t('event.soldOut'),
          })
        );
      }

      item.append(
        name,
        el('span', {
          className: 'ticket__price',
          text: ticket.price === 0 ? t('event.free') : formatPrice(ticket.price),
        })
      );
      list.append(item);
    });
    panel.append(list);
  }

  if (event.eventState === 'past') {
    // A <button disabled> rather than a dead link: there is nothing to book.
    panel.append(
      el('button', {
        className: 'button button--block',
        text: t('event.registerClosed'),
        attributes: { type: 'button', id: 'register-button', disabled: 'disabled' },
      })
    );
  } else {
    panel.append(
      el('a', {
        className: 'button button--block',
        text: t('event.register'),
        attributes: {
          id: 'register-button',
          // The event id travels in the query string, exactly as the brief
          // suggests: "You may utilise appropriate methods (e.g., URL Query
          // Strings or Local Storage) to pass the event ID between pages".
          href: `${REGISTRATION_PAGE}?id=${encodeURIComponent(event.eventId)}`,
        },
      })
    );
  }

  /*
   * The old A2 paragraph used to sit here ("Registering and paying for tickets
   * online is being built in Assessment 3"). It has been removed on purpose:
   * Assessment 3 built that feature, so the sentence was both out of date and
   * misleading, and the form it referred to is gone as well - the button above
   * now links to registration.html.
   */

  return panel;
}

/** Contact panel for the organisation running the event. */
function buildOrganiserPanel(event) {
  const panel = el('div', { className: 'panel' });
  panel.append(el('h2', { text: t('event.organisedBy') }));
  panel.append(el('h3', { text: event.organizationName }));
  panel.append(el('p', { text: t('event.organiserBody') }));
  const list = el('ul', { className: 'contact-list' });
  const city = el('li');
  city.append(el('span', { text: t('event.basedIn') }), el('span', { text: event.city }));
  list.append(city);
  panel.append(list);
  panel.append(
    // An anchor, not a paragraph. This was built with el('p', ...) carrying an
    // href and the .button classes, so it looked exactly like a button and did
    // nothing at all when clicked: a paragraph has no href behaviour.
    el('a', {
      className: 'button button--small button--outline',
      text: t('event.moreEvents'),
      attributes: { href: 'search.html' },
    })
  );
  return panel;
}

/* ------------------------------------------------------------------ */
/* Fallbacks                                                           */
/* ------------------------------------------------------------------ */

/** Shown when no id is present in the URL or in localStorage. */
function renderMissingId() {
  const root = select('#event-root');
  showError(root, t('event.noIdTitle'), [t('event.noIdHint')]);
  appendBackLink(root);
}

/** A safe way back if something went wrong. */
function appendBackLink(root) {
  const container = root.querySelector('.container') || root;
  const paragraph = el('p');
  paragraph.style.textAlign = 'center';
  paragraph.append(
    el('a', {
      className: 'button button--outline',
      text: t('error.backHome'),
      attributes: { href: 'index.html' },
    }),
    el('a', {
      className: 'button button--ghost',
      text: t('error.searchForEvent'),
      attributes: { href: 'search.html' },
    })
  );
  container.append(paragraph);
}
